FROM openjdk:17.0.1-jdk-oracle
#telur, gula, tepung, ragi, susu, coklat

# direktori
WORKDIR /app
#mangkok/loyang

# copy jar file
COPY target/*.jar app.jar

# expose
EXPOSE 8084

# run
CMD ["java", "-jar", "app.jar"]