## YAML Template.
---
server:
    port: 9000
    
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
                mvc:
                    routes:
                        - id: PRODUK-SERVICE
                          uri: lb://PRODUCT-SERVICE
                          predicates: 
                            - Path=api/produk
                        - id: PELANGGAN-SERVICE
                          uri: lb://PELANGGAN-SERVICE
                          predicates: 
                            - Path=api/pelanggan
                        - id: ORDER-SERVICE
                          uri: lb://ORDER-SERVICE
                          predicates: 
                            - Path=api/orders
                    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance: 
        hostname: localhost