pipeline {
    agent any

    environment {
        // --- KONFIGURASI KHUSUS ANGGOTA SERVICE ---
        SERVICE_NAME = 'anggotaservice'
        DOCKER_DIR = 'PerpustakaanService/anggotaservice' 
        K8S_DEPLOYMENT = 'anggota-deployment'
        K8S_NS = 'perpustakaan-ns'
        // Nama container di dalam file YAML deployment (biasanya anggota-container)
        CONTAINER_NAME = 'anggota-container'
        
        // Gunakan Tag Statis 1.0 agar hemat penyimpanan
        IMAGE_TAG = "localhost:5000/${SERVICE_NAME}:1.0"
    }

    tools {
        maven 'maven-3'
    }

    stages {
        stage('Initialize') {
            steps {
                // Setup Docker & Kubectl client di Jenkins
                sh '''
                if ! command -v docker &> /dev/null; then
                    curl -fsSL https://get.docker.com -o get-docker.sh
                    sh get-docker.sh
                fi
                if ! command -v kubectl &> /dev/null; then
                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                    chmod +x kubectl
                    mv kubectl /usr/local/bin/
                fi
                '''
            }
        }

        stage('Build Maven') {
            steps {
                dir("${DOCKER_DIR}") {
                    // Skip test agar cepat (2-3 menit)
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${DOCKER_DIR}") {
                    sh "docker build -t ${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Image') {
            steps {
                sh "docker push ${IMAGE_TAG}"
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                // Update image di deployment
                sh """
                kubectl set image deployment/${K8S_DEPLOYMENT} \
                ${CONTAINER_NAME}=${IMAGE_TAG} \
                -n ${K8S_NS}
                """
                
                // Restart rollout agar pod baru terambil
                sh "kubectl rollout restart deployment/${K8S_DEPLOYMENT} -n ${K8S_NS}"
            }
        }
    }
        // Bersihkan image sampah
    post {
        always {
            sh 'docker image prune -f'
        }
    }
}