apiVersion: v1
kind: Pod
metadata:
  name: productservice-pod
  labels:
    app: productservice
spec:
  containers:
    - name: productservice-container
      image: productservice:1.0
      ports:
        - containerPort: 8081
      env:
        - name: SERVER_PORT
          value: "8081"

        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://host.docker.internal:8761/eureka"
# self-healing
# mesin = discovery service

# qc = quality control

